name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
env:
  var1: abc
  var2: xyz

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Print Environment
        run: env | sort
      - name: Inject Variables
        uses: lindluni/actions-variable-groups@v2.1.2
        with:
          org: customer-success-architects
          repo: VariablesYAMLTest
          groups: |
            var2.yml 
