name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
env:
  var1: abc
  var2: xyz

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          echo ${{ env.var1 }} 
          echo ${{ env.var2 }} 
      - name: Inject Variables
        uses: lindluni/actions-variable-groups@v2.1.2
        with:
          repo: EYYAMLTEST
          groups: |
            Variables/var1.yml 
      - name: Print Environment
        run: env | sort
